#!/usr/bin/env bash
# plan-tasks.sh — DAG task planning for multi-coder
# Converts a free-text goal into a structured plan.md with task dependencies.
# Usage: ./plan-tasks.sh "Add user authentication with JWT tokens"

set -euo pipefail

GOAL="${1:?Usage: plan-tasks.sh '<goal description>'}"
OUTPUT_DIR="${2:-.}"
PLAN_FILE="${OUTPUT_DIR}/plan.md"

# ============================================================
# Phase 0: Impact Analysis
# ============================================================

echo "=== Phase 0: Impact Analysis ==="
echo "Goal: ${GOAL}"

# Scan affected files by common patterns
echo ""
echo "Scanning affected files..."

AFFECTED_FILES=()

# Search for files related to the goal keywords
for keyword in ${GOAL}; do
  found=$(find . -type f \( -name "*.ts" -o -name "*.tsx" -o -name "*.js" -o -name "*.jsx" -o -name "*.py" -o -name "*.go" -o -name "*.java" -o -name "*.rs" -o -name "*.css" -o -name "*.html" \) 2>/dev/null | grep -i "${keyword}" || true)
  if [ -n "${found}" ]; then
    AFFECTED_FILES+=("${found}")
  fi
done

# Also check for common config files
for config in "package.json" "requirements.txt" "go.mod" "Cargo.toml" "pom.xml" "tsconfig.json" ".env.example" "docker-compose.yml"; do
  if [ -f "${config}" ]; then
    AFFECTED_FILES+=("${config}")
  fi
done

# Deduplicate
AFFECTED_FILES=($(printf '%s\n' "${AFFECTED_FILES[@]}" | sort -u))

echo "Found ${#AFFECTED_FILES[@]} potentially affected files"

# ============================================================
# Generate plan.md
# ============================================================

cat > "${PLAN_FILE}" << 'HEADER'
# Task Plan — Auto-generated by plan-tasks.sh

HEADER

cat >> "${PLAN_FILE}" << EOF
## Goal

${GOAL}

## Affected Files

$(printf -- '- %s\n' "${AFFECTED_FILES[@]}")

## Task DAG

### Wave 1: Discovery
- [ ] T1: Analyze current architecture and identify change points
- [ ] T2: Define interface contracts (types, APIs, schemas)

### Wave 2: Implementation
- [ ] T3: Implement core logic (depends: T1, T2)
- [ ] T4: Add/update tests (depends: T2)

### Wave 3: Verification
- [ ] T5: Run full test suite (depends: T3, T4)
- [ ] T6: Security Gate review (depends: T3)
- [ ] T7: Adversarial review (depends: T3)

### Wave 4: Delivery
- [ ] T8: Final integration check (depends: T5, T6, T7)
- [ ] T9: Update documentation (depends: T8)

## Dependencies

\`\`\`
T1 ─┬─→ T3 ──→ T5 ──┬─→ T8 ──→ T9
T2 ─┘      ↑        │
           │        │
T2 ──→ T4 ─┘        │
                    │
              T6 ───┤
              T7 ───┘
\`\`\`

## Constraints

- Interface contracts from T2 are immutable once set
- Main CC is the sole writer; subagents are read-only
- Max 5 parallel subagents per wave
- All changes must pass tests + security gate before merge

EOF

echo "Plan written to ${PLAN_FILE}"
